# -*- coding: utf-8 -*-
"""UTS_ML2_221351023.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f0YUjS6hNaA9SkLA7l83CJLhLgqnI04B

#Identitas Diri

NIM  : 221351023<br>
Nama : Azzukhuf Fathan Amar<br>
Kelas: Pagi C<br>
Matkul: ML (Machine Learning)

# Business Understanding

## Project Domain

Domain ini termasuk dalam agriculture dan food safety dengan pendekatan classification problem dalam supervised learning.

## Problem Statements

Bagaimana cara memprediksi apakah jamur beracun atau tidak berdasarkan fitur seperti bentuk cap, warna, bau, dll?

## Goals

Membangun model ANN yang mampu memprediksi apakah jamur beracun (poisonous) atau tidak (edible) secara akurat.

## Solution Statements

Menerapkan ANN menggunakan TensorFlow/Keras, dilatih pada data jamur yang telah diproses dan divisualisasikan sebelumnya.

# Data Understanding

## Import data dari kaggle
"""

from google.colab import files
files.upload()

!kaggle datasets download -d uciml/mushroom-classification

!mkdir mushroom-classification
!unzip mushroom-classification.zip -d mushroom-classification
!ls mushroom-classification

"""## Import Library yang dibutuhkan"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, accuracy_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import load_model

"""## Exploratory Data Analysis"""

df = pd.read_csv('mushroom-classification/mushrooms.csv')

df.head()

df.info()

df['class'].value_counts()

fig, axes = plt.subplots(3, 2, figsize=(18, 15))
fig.suptitle("Exploratory Data Analysis on Mushroom Dataset", fontsize=18)

# 1. Distribusi target class
sns.countplot(x="class", data=df, ax=axes[0, 0])
axes[0, 0].set_title("Distribusi Kelas (Edible vs Poisonous)")

# 2. Distribusi cap-shape/bentuk topi
sns.countplot(x="cap-shape", data=df, ax=axes[0, 1])
axes[0, 1].set_title("Distribusi Cap Shape")

# 3. Distribusi odor/bau
sns.countplot(x="odor", data=df, ax=axes[1, 0])
axes[1, 0].set_title("Distribusi Odor")

# 4. Distribusi habitat
sns.countplot(x="habitat", data=df, ax=axes[1, 1])
axes[1, 1].set_title("Distribusi Habitat")

# 5. Perbandingan gill-color terhadap class
sns.countplot(x="gill-color", hue="class", data=df, ax=axes[2, 0])
axes[2, 0].set_title("Gill Color terhadap Class")

# Hapus subplot kosong
fig.delaxes(axes[2, 1])

plt.tight_layout(rect=[0, 0, 1, 0.97])
plt.show()

"""# Data Preparation"""

# Pisahkan fitur dan label
X = df.drop('class', axis=1)
y = df['class']

# Encode semua kolom kategorikal
le = LabelEncoder()
for col in df.columns:
    df[col] = le.fit_transform(df[col])

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Encode y_train and y_test if needed (assuming 'class' is categorical)
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

# Encode all categorical columns in X_train and X_test
le = LabelEncoder()
for col in X_train.select_dtypes(include=['object']).columns:
    le.fit(pd.concat([X_train[col], X_test[col]], axis=0)) # Fit on combined train and test data for consistent encoding
    X_train[col] = le.transform(X_train[col])
    X_test[col] = le.transform(X_test[col])

"""# Modeling"""

model = Sequential()
model.add(Dense(64, input_dim=X.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()

from tensorflow.keras.utils import plot_model
plot_model(model, show_shapes = True)

# Training model
history = model.fit(X_train, y_train, epochs=20, batch_size=32, validation_split=0.2)

"""# Evaluation"""

# Plot loss & accuracy
plt.plot(history.history['accuracy'], label='train acc')
plt.plot(history.history['val_accuracy'], label='val acc')
plt.title('Model Accuracy')
plt.legend()
plt.show()

# Test set evaluation
y_pred = (model.predict(X_test) > 0.5).astype("int32")
print(classification_report(y_test, y_pred))

"""# Deployment"""

sample = X_test.iloc[0].values.reshape(1, -1)
pred = model.predict(sample)
print("Prediksi:", "Poisonous" if pred > 0.5 else "Edible")

"""## Model Simulation"""

import random
index = random.randint(0, len(X_test)-1)
sample = X_test.iloc[index].values.reshape(1, -1)
pred = model.predict(sample)
print("Prediksi:", "Poisonous" if pred > 0.5 else "Edible")
print("Label Asli:", "Poisonous" if y_test[index] == 1 else "Edible")

"""## Save Model"""

model.save("mushroom_ann_model.h5")
